export const portfolio = [
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/games-1.jpg',
        name: 'Desperados III Digital',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.5',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-2.jpg',
        name: 'Red Dead Redemption 2',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.5',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-3.jpg',
        name: 'Baldur Gate II',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.5',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-4.jpg',
        name: 'HAND OF GILGAMECH',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.5',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-5.jpg',
        name: 'SteamWorld Quest Ryndo',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.2',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-6.jpg',
        name: 'A Puzzle of Flesh',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.2',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-7.jpg',
        name: 'We are the Dwarves',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.2',
        price: '28.99',
    },
    {
        image: 'https://themescare.com/demos/faf-v2/assets/img/game-8.jpg',
        name: 'Blood of the Sacred',
        genre: 'Action',
        releaseDate: '07.12.2015',
        rating: '4.2',
        price: '28.99',
    },
];